asm -> line
asm -> line lines

lines -> NEWLINE line
lines -> lines NEWLINE line

line -> opt_code opt_comment

opt_code -> 
opt_code -> opt_code SPACE
opt_code -> opt_code HEX HEX

opt_comment ->
opt_comment -> SLASH SLASH opt_comment_content

opt_comment_content -> 
opt_comment_content -> opt_comment_content SPACE
opt_comment_content -> opt_comment_content HEX
opt_comment_content -> opt_comment_content SLASH
opt_comment_content -> opt_comment_content OTHER

SPACE := [ \t]
HEX := [0-9a-fA-F]
NEWLINE := [\r\n]
SLASH := '/'
OTHER := [^ \t0-9a-fA-F\r\n/]

##
Thanks to @mdaines with his [context-free grammar tool](https://github.com/mdaines/grammophone) to help make the grammar SLR(1)!
